-- Seed 001: eliminado por decisión de producto
--
-- El CRM arranca completamente en blanco: las tablas users, concesionarios,
-- interacciones_crm y expansiones inician vacías, sin datos de prueba.
--
-- Cualquier registro semilla previamente insertado en un entorno existente se
-- limpia con la migración 005_limpiar_datos_semilla.sql.
